# keel_api/src/llm/tools/executors.py
"""Code-owned map of tool name -> async executor (binds DB catalog rows to runtime)."""

from __future__ import annotations

from llm.tools.contracts import ToolExecutor
from llm.tools.native.contacts import get_contact, list_contacts, search_contacts
from llm.tools.native.core import get_current_time
from llm.tools.native.focus import (
    create_focus_entry,
    create_focus_list,
    create_focus_tag,
    delete_focus_entry,
    delete_focus_list,
    delete_focus_tag,
    get_focus_list,
    list_focus_entries,
    list_focus_lists,
    list_focus_tags,
    update_focus_entry,
    update_focus_list,
    update_focus_tag,
)
from llm.tools.native.haul import (
    clear_finance_transaction_cover,
    create_finance_transaction,
    create_finance_vendor,
    delete_finance_transaction,
    delete_finance_transaction_media,
    delete_finance_vendor,
    fetch_listing,
    get_finance_transaction,
    list_finance_transaction_media,
    list_finance_transactions,
    list_finance_vendors,
    mark_finance_transaction_ordered,
    mark_finance_transaction_received,
    propose_finance_listing,
    set_finance_transaction_cover,
    set_finance_transaction_cover_from_url,
    update_finance_transaction,
    update_finance_vendor,
)
from llm.tools.native.obsidian import (
    vault_append_file,
    vault_create_directory,
    vault_delete_file,
    vault_list_entries,
    vault_move_file,
    vault_patch_file,
    vault_read_file,
    vault_search_notes,
    vault_write_file,
)
from llm.tools.native.projects import (
    create_project,
    create_project_tag,
    delete_project,
    delete_project_tag,
    get_project,
    get_project_canvas,
    list_project_canvases,
    list_project_media,
    list_project_tags,
    list_projects,
    set_project_appearance,
    set_project_cover,
    update_project,
    update_project_canvas,
    update_project_tag,
)
from llm.tools.native.web import (
    web_crawl,
    web_extract,
    web_map,
    web_research,
    web_search,
)

TOOL_EXECUTORS: dict[str, ToolExecutor] = {
    "get_current_time": get_current_time.execute,
    "vault_read_file": vault_read_file.execute,
    "vault_list_entries": vault_list_entries.execute,
    "vault_search_notes": vault_search_notes.execute,
    "vault_write_file": vault_write_file.execute,
    "vault_append_file": vault_append_file.execute,
    "vault_patch_file": vault_patch_file.execute,
    "vault_delete_file": vault_delete_file.execute,
    "vault_move_file": vault_move_file.execute,
    "vault_create_directory": vault_create_directory.execute,
    "list_projects": list_projects.execute,
    "get_project": get_project.execute,
    "create_project": create_project.execute,
    "update_project": update_project.execute,
    "delete_project": delete_project.execute,
    "set_project_appearance": set_project_appearance.execute,
    "set_project_cover": set_project_cover.execute,
    "list_project_tags": list_project_tags.execute,
    "create_project_tag": create_project_tag.execute,
    "update_project_tag": update_project_tag.execute,
    "delete_project_tag": delete_project_tag.execute,
    "list_project_media": list_project_media.execute,
    "get_project_canvas": get_project_canvas.execute,
    "list_project_canvases": list_project_canvases.execute,
    "update_project_canvas": update_project_canvas.execute,
    "list_finance_vendors": list_finance_vendors.execute,
    "create_finance_vendor": create_finance_vendor.execute,
    "update_finance_vendor": update_finance_vendor.execute,
    "delete_finance_vendor": delete_finance_vendor.execute,
    "list_finance_transactions": list_finance_transactions.execute,
    "get_finance_transaction": get_finance_transaction.execute,
    "create_finance_transaction": create_finance_transaction.execute,
    "update_finance_transaction": update_finance_transaction.execute,
    "delete_finance_transaction": delete_finance_transaction.execute,
    "list_finance_transaction_media": list_finance_transaction_media.execute,
    "delete_finance_transaction_media": delete_finance_transaction_media.execute,
    "set_finance_transaction_cover": set_finance_transaction_cover.execute,
    "clear_finance_transaction_cover": clear_finance_transaction_cover.execute,
    "mark_finance_transaction_ordered": mark_finance_transaction_ordered.execute,
    "mark_finance_transaction_received": mark_finance_transaction_received.execute,
    "fetch_listing": fetch_listing.execute,
    "propose_finance_listing": propose_finance_listing.execute,
    "set_finance_transaction_cover_from_url": set_finance_transaction_cover_from_url.execute,
    "web_search": web_search.execute,
    "web_extract": web_extract.execute,
    "web_map": web_map.execute,
    "web_crawl": web_crawl.execute,
    "web_research": web_research.execute,
    "list_focus_lists": list_focus_lists.execute,
    "get_focus_list": get_focus_list.execute,
    "create_focus_list": create_focus_list.execute,
    "update_focus_list": update_focus_list.execute,
    "delete_focus_list": delete_focus_list.execute,
    "list_focus_entries": list_focus_entries.execute,
    "create_focus_entry": create_focus_entry.execute,
    "update_focus_entry": update_focus_entry.execute,
    "delete_focus_entry": delete_focus_entry.execute,
    "list_focus_tags": list_focus_tags.execute,
    "create_focus_tag": create_focus_tag.execute,
    "update_focus_tag": update_focus_tag.execute,
    "delete_focus_tag": delete_focus_tag.execute,
    "list_contacts": list_contacts.execute,
    "get_contact": get_contact.execute,
    "search_contacts": search_contacts.execute,
}
