// keel_web/src/lib/keelPersona/presetIds.ts

/** Stable preset ids referenced by promoted clips and Tesla glow routing. */
export const KEEL_PERSONA_PRESET_IDS = {
  leftEyeStraight: "preset-left-eye-straight",
  rightEyeStraight: "preset-right-eye-straight",
  leftEyeLine1: "preset-left-eye-line-1",
  leftEyeLine2: "preset-left-eye-line-2",
  leftEyeLine3: "preset-left-eye-line-3",
  leftEyeLine4: "preset-left-eye-line-4",
  leftEyeLine5: "preset-left-eye-line-5",
  rightEyeLine1: "preset-right-eye-line-1",
  rightEyeLine2: "preset-right-eye-line-2",
  rightEyeLine3: "preset-right-eye-line-3",
  rightEyeLine4: "preset-right-eye-line-4",
  rightEyeLine5: "preset-right-eye-line-5",
  leftInnerEyeLine1: "preset-left-inner-eye-line-1",
  leftInnerEyeLine2: "preset-left-inner-eye-line-2",
  leftInnerEyeLine3: "preset-left-inner-eye-line-3",
  leftInnerEyeLine4: "preset-left-inner-eye-line-4",
  leftInnerEyeLine5: "preset-left-inner-eye-line-5",
  rightInnerEyeLine1: "preset-right-inner-eye-line-1",
  rightInnerEyeLine2: "preset-right-inner-eye-line-2",
  rightInnerEyeLine3: "preset-right-inner-eye-line-3",
  rightInnerEyeLine4: "preset-right-inner-eye-line-4",
  rightInnerEyeLine5: "preset-right-inner-eye-line-5",
  mouthOuterLine1: "preset-mouth-outer-line-1",
  mouthOuterLine2: "preset-mouth-outer-line-2",
  mouthOuterLine3: "preset-mouth-outer-line-3",
  mouthInnerLine3: "preset-mouth-inner-line-3",
  mouthOuterLine5: "preset-mouth-outer-line-5",
  mouthInnerLine1: "preset-mouth-inner-line-1",
  mouthInnerLine2: "preset-mouth-inner-line-2",
  mouthOuterLine4: "preset-mouth-outer-line-4",
  mouthInnerLine4: "preset-mouth-inner-line-4",
  mouthInnerLine5: "preset-mouth-inner-line-5",
} as const;
